### ISSUE TITLE
Fatal error: incompatible declaration of get method against PSR interface, in some PHP versions

### ISSUE THREAD

**Issue by remyperona** [thephpleague/container#227]
Hi,

Reporting this fatal error we encountered with the container recently.

As a note, it happened only on specific PHP versions, an example being PHP 7.1.33. Didn't have the issue with 7.2/3/4 though.

`Fatal error: Declaration of League\Container\Container::get($alias, array $args = Array) must be compatible with Psr\Container\ContainerInterface::get(string $id) in Container/Container.php on line 16`

A recent minor release of the psr/container is likely the cause, as can be seen on: https://github.com/php-fig/container/issues/30

To fix the issue we forced the `psr/container` version to `1.0.0` for now in our projects, but I thought it would be a good idea to notify you in case you were not aware.

**Comment by philipobenito** [comment]
Thanks, this is an oversight with the most recent release, will get a fix released asap

**Comment by joshua-graham-adelphi** [comment]
For those still encountering this from google search. In Drupal 8/9, I see this issue if using PHP 7.1 (PHP 7.2+ has no issue), it is fixed with using composer package `drupal/core-recommended` which sets the the dependencies (such as this) to compatible versions.

If you have an issue switching to it, this migrate script may be of use. https://github.com/mstrelan/drupal-core-recommended-migrate

**Comment by hron84** [comment]
@joshua-graham-adelphi please write affected dependencies against this issue. I'm still encountering this problem and it seems an endless fight. It also comes with 7.3 too.

**Comment by joshua-graham-adelphi** [comment]
Looks this there is bug with PHP 7.1 that stops the code from running (https://bugs.php.net/bug.php?id=75682). This was fixed in PHP 7.2 not applied to 7.1 in a minor release due to backwards compatibility of existing broken code.

Technical reason:
psr/container -> ContainerInterface::get($id) [1.0.0] changed to  ContainerInterface::get(string $id) [with declare(strict_types=1); ] in 1.1+
Which seems not compatible in PHP 7.1 with League\Container\Container::get($alias, array $args = Array)
Note the primitive type hint change.

Fix is to use psr/container 1.0.0 if PHP 7.1 or upgrade php version to PHP 7.2 +. I'm not sure if this project repo can fixed easily.

<details>
  <summary>Research:</summary>
[works]
$  composer why --tree psr/container
psr/container 1.0.0 Common Container Interface (PHP FIG PSR-11)
|--container-interop/container-interop 1.2.0 (requires psr/container ^1.0)
│  └──league/container 2.5.0 (requires container-interop/container-interop ^1.2)
│     ├──consolidation/robo 1.4.13 (requires league/container ^2.4.1)
│     │  └──drush/drush 10.5.0 (requires consolidation/robo ^1.4.11 || ^2)
│     │     └──drupal/drupal dev-master (requires drush/drush ^9.7.1|^10.0.0)
[...]
|--symfony/dependency-injection v3.4.41 (requires psr/container ^1.0)
   ├──drupal/core 8.9.16 (requires symfony/dependency-injection ~3.4.26)

[broken]
psr/container 1.1.1 Common Container Interface (PHP FIG PSR-11)
├──container-interop/container-interop 1.2.0 (requires psr/container ^1.0)
│  └──league/container 2.5.0 (requires container-interop/container-interop ^1.2)
│     ├──consolidation/robo 1.4.13 (requires league/container ^2.4.1)
│     │  ├──consolidation/robo 1.4.13 (replaces codegyre/robo < 1.0)
│     │  └──drush/drush 10.5.0 (requires consolidation/robo ^1.4.11 || ^2)
│     │     └──drupal/drupal dev-b071ef005805bc30ce1a1950ad4b02584ad7573c (requires drush/drush ^9.7.1|^10.0.0)
[...]
└──symfony/dependency-injection v3.4.47 (requires psr/container ^1.0)
   └──drupal/core 8.9.15 (requires symfony/dependency-injection ~3.4.26)

[drush/drush 8.4.8 error - psr/container 1.1.1 + dependency-injection v3.4.47]
PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE) must be compatible with Psr\Container\ContainerInterface::get(string $id) in [project]\vendor\symfony\dependency-injection\ContainerInterface.php on line 25

[drush/drush 10.5.0 error - league/container 2.5.0 + psr/container 1.1.1]
PHP Fatal error:  Declaration of League\Container\Container::get($alias, array $args = Array) must be compatible with Psr\Container\ContainerInterface::get(string $id) in C:\Projects\aspi-dev\docroot\vendor\league\container\src\Container.php on line 16

[Psr\Container\ContainerInterface]
https://github.com/php-fig/container/blob/1.1.1/src/ContainerInterface.php => ContainerInterface::get(string $id) [with declare(strict_types=1); in the file]
https://github.com/php-fig/container/blob/1.1.0/src/ContainerInterface.php => ContainerInterface::get(string $id) [with declare(strict_types=1); in the file]
https://github.com/php-fig/container/blob/1.0.0/src/ContainerInterface.php => ContainerInterface::get($id)

[Psr\Container\ContainerInterface]
[Note that this ContainerInterface extends Psr\Container\ContainerInterface]
https://github.com/symfony/dependency-injection/blob/v3.4.47/ContainerInterface.php => ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE);
https://github.com/symfony/dependency-injection/blob/v3.4.41/ContainerInterface.php => ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE);
</details>

**Comment by philipobenito** [comment]
3.4.0 has been released with a revert to only use `psr/container:^1.0.0`
4.0.0 has been released which has a PHP requirement of `>=7.2` meaning `psr/container` can be safely implemented
